# Generated by Django 3.0.4 on 2022-05-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatTheFuvk',
        ),
    ]
