# Generated by Django 3.0.4 on 2022-05-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_whatthefuvk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_accepted', to='users.Profile')),
                ('member_started', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_started', to='users.Profile')),
            ],
        ),
    ]
