# Generated by Django 3.0.4 on 2022-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default=101, max_length=12),
            preserve_default=False,
        ),
    ]
